name: pexels_sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.6
  infinite_scroll_pagination: ^4.0.0
  logger: ^2.2.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

msix_config:
  display_name: Pexels Sample
  publisher_display_name: Dharam Budh
  identity_name: com.example.pexels-sample
  msix_version: 1.0.0.0
  logo_path: assets\images\flutter.png
  languages: en-us
  capabilities: internetClient
  certificate_path: windows_certificates\pexels-sample.pfx
  certificate_password: 123456
